### ISSUE TITLE
Version 1.0.6 of gaxios doesn't seem to have any *.js files in it

### ISSUE THREAD

**Issue by aalexand** [JustinBeckwith/gaxios#13]
Saw this while investigating `"Error: Cannot find module 'gaxios'" ` error that started happening for my program today. See below, it seems version 1.0.2 has "build" directory but version 1.0.6 that was released today does not.

```
@azina:node_modules$
@azina:test$ npm install gaxios@1.0.2
...
+ gaxios@1.0.2
updated 1 package and audited 524 packages in 0.638s
found 0 vulnerabilities

@azina:test$ ls node_modules/gaxios/
LICENSE  README.md  build  package.json


@azina:test$ npm install gaxios@1.0.6
...
+ gaxios@1.0.6
updated 1 package and audited 524 packages in 0.76s
found 0 vulnerabilities

@azina:test$ ls node_modules/gaxios/
LICENSE  README.md  package.json
```

**Comment by emileae** [comment]
+1 from me, Just came across the same problem now also investigating Error: Cannot find module 'gaxios'

**Comment by xavhan** [comment]
@google/gcp-metadata module use is with an unpinned version causing our build to crash too.

**Comment by lamstutz** [comment]
+1

**Comment by vranystepan** [comment]
@xavhan Yeah, I'm struggling with the same module :)

**Comment by ggunia** [comment]
+1

**Comment by codyzu** [comment]
For the maintainers: please delete that bad package from npm ASAP, this brakes @google-cloud/trace-agent especially when deploying to google cloud functions (where the package-lock.json and yarn.lock files are not respected).

**Comment by duff907** [comment]
We're having the same issue as @codyzu described. We've managed to get round it by adding gaxios as a dependency in our `package.json` and the fixing the version at `1.0.4`. This works for the short term.

**Comment by JustinBeckwith** [comment]
Oh my word, apologies folks.  This release obviously should not have gone out :(  I just pushed `1.0.7` which resolves the issue.  Apologies again!
