### ISSUE TITLE
Support cancellation like Axios

### ISSUE THREAD

**Issue by acchou** [JustinBeckwith/gaxios#31]
With [google-api-nodejs-client](https://github.com/googleapis/google-api-nodejs-client)'s move from Axios to gaxios, the [cancellation feature](https://github.com/axios/axios#cancellation) has been lost. This turns out to be important for certain use cases. 

For example, the PubSub pull API has an option to return immediately or wait for some messages to arrive. Waiting for some messages is desirable if polling in a loop, so the loop doesn't poll overly frequently causing a high request volume and incurring costs for each request. But if the client decides to cancel the request, it may be stuck waiting for an indeterminate amount of time without the ability to cancel the request.

The ideal solution would be to support the same cancellation semantics as Axios, or some other cancellation API.

**Comment by trulyshelton** [comment]
Another related issue:  if a user abort a download prematurely, then the stream is not going to be fully consumed, leaving the request just sitting idle and without a way to cancel it.
