### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by tejohnso** [JustinBeckwith/gaxios#81]
> Only really useful if you're trying to migrate from axios to the fetch

It might be helpful to indicate why someone would be inclined to make this migration. At least, as a sample of 1, count me as curious.

**Comment by JustinBeckwith** [comment]
Greetings!  We were originally using axios, but created this for a few reasons:
- Axios has been relatively unmaintained recently
- It didn't support proxy support out of the box
- It didn't support retry out of the box
- It duplicated a lot of client side logic we just didn't need here

Axios is a great library, but we wanted something built on the much lighter node-fetch.  Hope this helps!
