### ISSUE TITLE
The latest release (1.8.5) breaks for node 6.10 on google-auth-library@2.0.0

### ISSUE THREAD

**Issue by nishant-lbb** [JustinBeckwith/gaxios#86]
Getting this : node_modules/gaxios/build/src/index.js:28
async function request(opts) {
      ^^^^^^^^
SyntaxError: Unexpected token function

**Comment by kubicle** [comment]
We get the same one.

**Comment by AndrewSolonovich** [comment]
Have the same issue. Is there a possible workaround?

**Comment by nishant-lbb** [comment]
I explicitly defined gaxios: 1.8.4 as a top level dependency. That seemed to work for us.

**Comment by ThamiduNaveen** [comment]
same issue async function request(opts) {
^^^^^^^^
SyntaxError: Unexpected token function

**Comment by kechkibet** [comment]
Following, breaks my firebase functions when i try to use admin

**Comment by m4recek** [comment]
Cant deploy our Firebase projects on Node 6 because of this. Dropping Node version should be done as major release.

**Comment by kechkibet** [comment]
I had to change the engine on firebase functions to node 8 for it to work. as per this link:
https://firebase.google.com/docs/functions/manage-functions

"engines": {"node": "8"}

**Comment by m4recek** [comment]
@kechkibet there is a unfixed problem with Node 8 in Firebase https://github.com/firebase/firebase-functions/issues/429

**Comment by JustinBeckwith** [comment]
Greetings folks!  Apologies for the problems.  This was supposed to be a semver major bump, and something went wrong in the automated release machinery.  I un-published `gaxios@1.8.5`, and ensured the `dist` tag is set to `gaxios@1.8.4`.  We will be digging into what happened here today.  

Can someone delete their `package-lock.json`, `npm install`, and verify this still works?

**Comment by m4recek** [comment]
It works. Thank you for quick resolution :)

**Comment by ThamiduNaveen** [comment]
@m4recek is that connection error on 8 appear frequently?. In which cases that appear?

**Comment by m4recek** [comment]
@ThamiduNaveen very frequently, we have scraped production update to Node 8 because of it. More is here https://github.com/firebase/firebase-functions/issues/429
