### ISSUE TITLE
gaxios fails with jest

### ISSUE THREAD

**Issue by adriano-di-giovanni** [JustinBeckwith/gaxios#87]
The default test environment that [Jest](https://jestjs.io/) uses for testing is a browser-like one through [jsdom](https://github.com/tmpvar/jsdom).

The browser-like environment makes your [following line of code](https://github.com/JustinBeckwith/gaxios/blob/master/src/gaxios.ts#L34) fail:

```javascript
const fetch = isBrowser() ? window.fetch : nodeFetch;
```

because `typeof window !== 'undefined'` in `isBrowser()` evaluates to true but `window.fetch` is undefined.

Maybe, you can directly check against the existence of `window.fetch` instead of relying on `isBrowser`.

If you agree, I can send you a PR to replace each and every check against `isBrowser` with a feature-detection check.

**Comment by adriano-di-giovanni** [comment]
I'd like to add that it is possible to change the [test environment](https://jestjs.io/docs/en/configuration#testenvironment-string) that Jest uses for testing but I think that a feature-detection style improves the quality of the check your code relies on.

**Comment by JustinBeckwith** [comment]
Greetings @adriano-di-giovanni, and thanks for the issue!  Something like what you suggested sounds reasonable.  I'd love a PR!
